---
title: "ped_counts"
author: "Dana Kraushar"
date: "5/7/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
peds <- read_csv("PedCountLocationsMay2015.csv")

peds$the_geom <- str_remove_all(peds$the_geom, "POINT ")

peds <- separate(peds, the_geom, c("long", "lat"), " ", remove=TRUE)

# peds$the_geom <- str_split_fixed(test, " ", 2)

# test3 <- str_replace_all(test2, "", "")

peds$long <- gsub("^.", "", peds$long)
peds$lat <- gsub(".$", "", peds$lat)

peds$long <- as.numeric(peds$long)
peds$lat <- as.numeric(peds$lat)

# # filter rows that are not one of the 5 boroughs (exclude locations on bridges)
# peds$Borough %>% unique
table(peds$Borough)
peds %>% filter(Borough != "East River Bridges" & Borough != "Harlem River Bridges")
```

```{r}
peds_by_borough <- peds %>% 
                    group_by(Borough) %>%
                    summarize(
                              total_May07_AM = sum(May07_AM),
                              total_May07_MD = sum(May07_MD),
                              total_May07_PM = sum(May07_PM),
                              
                              total_Sept07_AM = sum(Sept07_AM),
                              total_Sept07_MD = sum(Sept07_MD),
                              total_Sept07_PM = sum(Sept07_PM),
                              
                              total_May08_AM = sum(May08_AM),
                              total_May08_MD = sum(May08_MD),
                              total_May08_PM = sum(May08_PM),
                              
                              total_Sept08_AM = sum(Sept08_AM),
                              total_Sept08_MD = sum(Sept08_MD),
                              total_Sept08_PM = sum(Sept08_PM),
                              
                              total_May09_AM = sum(May09_AM),
                              total_May09_MD = sum(May09_MD),
                              total_May09_PM = sum(May09_PM),
                              
                              total_Sept09_AM = sum(Sept09_AM),
                              total_Sept09_MD = sum(Sept09_MD),
                              total_Sept09_PM = sum(Sept09_PM),                              
                              
                              total_May10_AM = sum(May10_AM),
                              total_May10_MD = sum(May10_MD),
                              total_May10_PM = sum(May10_PM),
                              
                              total_Sept10_AM = sum(Sept10_AM),
                              total_Sept10_MD = sum(Sept10_MD),
                              total_Sept10_PM = sum(Sept10_PM),    
                              
                              total_May11_AM = sum(May11_AM),
                              total_May11_MD = sum(May11_MD),
                              total_May11_PM = sum(May11_PM),
                              
                              total_Sept11_AM = sum(Sept11_AM),
                              total_Sept11_MD = sum(Sept11_MD),
                              total_Sept11_PM = sum(Sept11_PM),
                              
                              total_May12_AM = sum(May12_AM),
                              total_May12_MD = sum(May12_MD),
                              total_May12_PM = sum(May12_PM),
                              
                              total_Sept12_AM = sum(Sept12_AM),
                              total_Sept12_MD = sum(Sept12_MD),
                              total_Sept12_PM = sum(Sept12_PM),
                              
                              total_May13_AM = sum(May13_AM),
                              total_May13_MD = sum(May13_MD),
                              total_May13_PM = sum(May13_PM),
                              
                              total_Sept13_AM = sum(Sept13_AM),
                              total_Sept13_MD = sum(Sept13_MD),
                              total_Sept13_PM = sum(Sept13_PM),
                              
                              total_May14_AM = sum(May14_AM),
                              total_May14_MD = sum(May14_MD),
                              total_May14_PM = sum(May14_PM),
                              
                              total_Sept14_AM = sum(Sept14_AM),
                              total_Sept14_MD = sum(Sept14_MD),
                              total_Sept14_PM = sum(Sept14_PM),                             
                        
                              total_May15_AM = sum(May15_AM),
                              total_May15_MD = sum(May15_MD),
                              total_May15_PM = sum(May15_PM)) %>%
  
                    mutate(
                              total_May07_AM = total_May07_AM,
                              total_May07_MD = total_May07_MD,
                              total_May07_PM = total_May07_PM,
                              
                              total_Sept07_AM = total_Sept07_AM,
                              total_Sept07_MD = total_Sept07_MD,
                              total_Sept07_PM = total_Sept07_PM,
                              
                              total_May08_AM = total_May08_AM,
                              total_May08_MD = total_May08_MD,
                              total_May08_PM = total_May08_PM,
                              
                              total_Sept08_AM = total_Sept08_AM,
                              total_Sept08_MD = total_Sept08_MD,
                              total_Sept08_PM = total_Sept08_PM,
                              
                              total_May09_AM = total_May09_AM,
                              total_May09_MD = total_May09_MD,
                              total_May09_PM = total_May09_PM,
                              
                              total_Sept09_AM = total_Sept09_AM,
                              total_Sept09_MD = total_Sept09_MD,
                              total_Sept09_PM = total_Sept09_PM,                              
                              
                              total_May10_AM = total_May10_AM,
                              total_May10_MD = total_May10_MD,
                              total_May10_PM = total_May10_PM,
                              
                              total_Sept10_AM = total_Sept10_AM,
                              total_Sept10_MD = total_Sept10_MD,
                              total_Sept10_PM = total_Sept10_PM,    
                              
                              total_May11_AM = total_May11_AM,
                              total_May11_MD = total_May11_MD,
                              total_May11_PM = total_May11_PM,
                              
                              total_Sept11_AM = total_Sept11_AM,
                              total_Sept11_MD = total_Sept11_MD,
                              total_Sept11_PM = total_Sept11_PM,
                              
                              total_May12_AM = total_May12_AM,
                              total_May12_MD = total_May12_MD,
                              total_May12_PM = total_May12_PM,
                              
                              total_Sept12_AM = total_Sept12_AM,
                              total_Sept12_MD = total_Sept12_MD,
                              total_Sept12_PM = total_Sept12_PM,
                              
                              total_May13_AM = total_May13_AM,
                              total_May13_MD = total_May13_MD,
                              total_May13_PM = total_May13_PM,
                              
                              total_Sept13_AM = total_Sept13_AM,
                              total_Sept13_MD = total_Sept13_MD,
                              total_Sept13_PM = total_Sept13_PM,
                              
                              total_May14_AM = total_May14_AM,
                              total_May14_MD = total_May14_MD,
                              total_May14_PM = total_May14_PM,
                              
                              total_Sept14_AM = total_Sept14_AM,
                              total_Sept14_MD = total_Sept14_MD,
                              total_Sept14_PM = total_Sept14_PM,                             
                        
                              total_May15_AM = total_May15_AM,
                              total_May15_MD = total_May15_MD,
                              total_May15_PM = total_May15_PM) %>%                        
                    filter(Borough != "East River Bridges" & Borough != "Harlem River Bridges")

```

```{r}
brooklyn_bridge_totals <- peds %>%
                            filter(Street == "Brooklyn Bridge") %>%
                    summarize(
                              total_May07_AM = sum(May07_AM),
                              total_May07_MD = sum(May07_MD),
                              total_May07_PM = sum(May07_PM),
                              
                              total_Sept07_AM = sum(Sept07_AM),
                              total_Sept07_MD = sum(Sept07_MD),
                              total_Sept07_PM = sum(Sept07_PM),
                              
                              total_May08_AM = sum(May08_AM),
                              total_May08_MD = sum(May08_MD),
                              total_May08_PM = sum(May08_PM),
                              
                              total_Sept08_AM = sum(Sept08_AM),
                              total_Sept08_MD = sum(Sept08_MD),
                              total_Sept08_PM = sum(Sept08_PM),
                              
                              total_May09_AM = sum(May09_AM),
                              total_May09_MD = sum(May09_MD),
                              total_May09_PM = sum(May09_PM),
                              
                              total_Sept09_AM = sum(Sept09_AM),
                              total_Sept09_MD = sum(Sept09_MD),
                              total_Sept09_PM = sum(Sept09_PM),                              
                              
                              total_May10_AM = sum(May10_AM),
                              total_May10_MD = sum(May10_MD),
                              total_May10_PM = sum(May10_PM),
                              
                              total_Sept10_AM = sum(Sept10_AM),
                              total_Sept10_MD = sum(Sept10_MD),
                              total_Sept10_PM = sum(Sept10_PM),    
                              
                              total_May11_AM = sum(May11_AM),
                              total_May11_MD = sum(May11_MD),
                              total_May11_PM = sum(May11_PM),
                              
                              total_Sept11_AM = sum(Sept11_AM),
                              total_Sept11_MD = sum(Sept11_MD),
                              total_Sept11_PM = sum(Sept11_PM),
                              
                              total_May12_AM = sum(May12_AM),
                              total_May12_MD = sum(May12_MD),
                              total_May12_PM = sum(May12_PM),
                              
                              total_Sept12_AM = sum(Sept12_AM),
                              total_Sept12_MD = sum(Sept12_MD),
                              total_Sept12_PM = sum(Sept12_PM),
                              
                              total_May13_AM = sum(May13_AM),
                              total_May13_MD = sum(May13_MD),
                              total_May13_PM = sum(May13_PM),
                              
                              total_Sept13_AM = sum(Sept13_AM),
                              total_Sept13_MD = sum(Sept13_MD),
                              total_Sept13_PM = sum(Sept13_PM),
                              
                              total_May14_AM = sum(May14_AM),
                              total_May14_MD = sum(May14_MD),
                              total_May14_PM = sum(May14_PM),
                              
                              total_Sept14_AM = sum(Sept14_AM),
                              total_Sept14_MD = sum(Sept14_MD),
                              total_Sept14_PM = sum(Sept14_PM),                             
                        
                              total_May15_AM = sum(May15_AM),
                              total_May15_MD = sum(May15_MD),
                              total_May15_PM = sum(May15_PM)) %>%
  
                    mutate(
                              total_May07_AM = total_May07_AM,
                              total_May07_MD = total_May07_MD,
                              total_May07_PM = total_May07_PM,
                              
                              total_Sept07_AM = total_Sept07_AM,
                              total_Sept07_MD = total_Sept07_MD,
                              total_Sept07_PM = total_Sept07_PM,
                              
                              total_May08_AM = total_May08_AM,
                              total_May08_MD = total_May08_MD,
                              total_May08_PM = total_May08_PM,
                              
                              total_Sept08_AM = total_Sept08_AM,
                              total_Sept08_MD = total_Sept08_MD,
                              total_Sept08_PM = total_Sept08_PM,
                              
                              total_May09_AM = total_May09_AM,
                              total_May09_MD = total_May09_MD,
                              total_May09_PM = total_May09_PM,
                              
                              total_Sept09_AM = total_Sept09_AM,
                              total_Sept09_MD = total_Sept09_MD,
                              total_Sept09_PM = total_Sept09_PM,                              
                              
                              total_May10_AM = total_May10_AM,
                              total_May10_MD = total_May10_MD,
                              total_May10_PM = total_May10_PM,
                              
                              total_Sept10_AM = total_Sept10_AM,
                              total_Sept10_MD = total_Sept10_MD,
                              total_Sept10_PM = total_Sept10_PM,    
                              
                              total_May11_AM = total_May11_AM,
                              total_May11_MD = total_May11_MD,
                              total_May11_PM = total_May11_PM,
                              
                              total_Sept11_AM = total_Sept11_AM,
                              total_Sept11_MD = total_Sept11_MD,
                              total_Sept11_PM = total_Sept11_PM,
                              
                              total_May12_AM = total_May12_AM,
                              total_May12_MD = total_May12_MD,
                              total_May12_PM = total_May12_PM,
                              
                              total_Sept12_AM = total_Sept12_AM,
                              total_Sept12_MD = total_Sept12_MD,
                              total_Sept12_PM = total_Sept12_PM,
                              
                              total_May13_AM = total_May13_AM,
                              total_May13_MD = total_May13_MD,
                              total_May13_PM = total_May13_PM,
                              
                              total_Sept13_AM = total_Sept13_AM,
                              total_Sept13_MD = total_Sept13_MD,
                              total_Sept13_PM = total_Sept13_PM,
                              
                              total_May14_AM = total_May14_AM,
                              total_May14_MD = total_May14_MD,
                              total_May14_PM = total_May14_PM,
                              
                              total_Sept14_AM = total_Sept14_AM,
                              total_Sept14_MD = total_Sept14_MD,
                              total_Sept14_PM = total_Sept14_PM,                             
                        
                              total_May15_AM = total_May15_AM,
                              total_May15_MD = total_May15_MD,
                              total_May15_PM = total_May15_PM)
```

```{r}
peds_by_borough <- peds_by_borough %>% 
                            mutate(
                                sum_May07 = total_May07_AM + total_May07_MD + total_May07_PM,
                                sum_Sept07 = total_Sept07_AM + total_Sept07_MD + total_Sept07_PM,
                                sum_2007 = sum_May07 + sum_Sept07,
                                
                                sum_May08 = total_May08_AM + total_May08_MD + total_May08_PM,
                                sum_Sept08 = total_Sept08_AM + total_Sept08_MD + total_Sept08_PM,
                                sum_2008 = sum_May08 + sum_Sept08,     
                                
                                sum_May09 = total_May09_AM + total_May09_MD + total_May09_PM,
                                sum_Sept09 = total_Sept09_AM + total_Sept09_MD + total_Sept09_PM,
                                sum_2009 = sum_May09 + sum_Sept09,   
                                
                                sum_May10 = total_May10_AM + total_May10_MD + total_May10_PM,
                                sum_Sept10 = total_Sept10_AM + total_Sept10_MD + total_Sept10_PM,
                                sum_2010 = sum_May10 + sum_Sept10,
                                
                                sum_May11 = total_May11_AM + total_May11_MD + total_May11_PM,
                                sum_Sept11 = total_Sept11_AM + total_Sept11_MD + total_Sept11_PM,
                                sum_2011 = sum_May11 + sum_Sept11,   
                                
                                sum_May12 = total_May12_AM + total_May12_MD + total_May12_PM,
                                sum_Sept12 = total_Sept12_AM + total_Sept12_MD + total_Sept12_PM,
                                sum_2012 = sum_May12 + sum_Sept12,  
                                
                                sum_May13 = total_May13_AM + total_May13_MD + total_May13_PM,
                                sum_Sept13 = total_Sept13_AM + total_Sept13_MD + total_Sept13_PM,
                                sum_2013 = sum_May13 + sum_Sept13,  
                                
                                sum_May14 = total_May14_AM + total_May14_MD + total_May14_PM,
                                sum_Sept14 = total_Sept14_AM + total_Sept14_MD + total_Sept14_PM,
                                sum_2014 = sum_May14 + sum_Sept14,       
                                
                                sum_May15 = total_May15_AM + total_May15_MD + total_May15_PM
                                   )

```

```{r}
brooklyn_bridge_totals <- brooklyn_bridge_totals %>% 
                            mutate(
                                sum_May07 = total_May07_AM + total_May07_MD + total_May07_PM,
                                sum_Sept07 = total_Sept07_AM + total_Sept07_MD + total_Sept07_PM,
                                sum_2007 = sum_May07 + sum_Sept07,
                                
                                sum_May08 = total_May08_AM + total_May08_MD + total_May08_PM,
                                sum_Sept08 = total_Sept08_AM + total_Sept08_MD + total_Sept08_PM,
                                sum_2008 = sum_May08 + sum_Sept08,     
                                
                                sum_May09 = total_May09_AM + total_May09_MD + total_May09_PM,
                                sum_Sept09 = total_Sept09_AM + total_Sept09_MD + total_Sept09_PM,
                                sum_2009 = sum_May09 + sum_Sept09,   
                                
                                sum_May10 = total_May10_AM + total_May10_MD + total_May10_PM,
                                sum_Sept10 = total_Sept10_AM + total_Sept10_MD + total_Sept10_PM,
                                sum_2010 = sum_May10 + sum_Sept10,
                                
                                sum_May11 = total_May11_AM + total_May11_MD + total_May11_PM,
                                sum_Sept11 = total_Sept11_AM + total_Sept11_MD + total_Sept11_PM,
                                sum_2011 = sum_May11 + sum_Sept11,   
                                
                                sum_May12 = total_May12_AM + total_May12_MD + total_May12_PM,
                                sum_Sept12 = total_Sept12_AM + total_Sept12_MD + total_Sept12_PM,
                                sum_2012 = sum_May12 + sum_Sept12,  
                                
                                sum_May13 = total_May13_AM + total_May13_MD + total_May13_PM,
                                sum_Sept13 = total_Sept13_AM + total_Sept13_MD + total_Sept13_PM,
                                sum_2013 = sum_May13 + sum_Sept13,  
                                
                                sum_May14 = total_May14_AM + total_May14_MD + total_May14_PM,
                                sum_Sept14 = total_Sept14_AM + total_Sept14_MD + total_Sept14_PM,
                                sum_2014 = sum_May14 + sum_Sept14,       
                                
                                sum_May15 = total_May15_AM + total_May15_MD + total_May15_PM
                                   )
```

```{r}
# transpose brooklyn bridge data

brooklyn_bridge_totals_t <- as.data.frame(t(brooklyn_bridge_totals))

brooklyn_bridge_totals_t2 <- as.data.frame(t(brooklyn_bridge_totals)) %>% rename(total = V1)
brooklyn_bridge_totals_t2 <- brooklyn_bridge_totals_t2 %>% rownames_to_column()
```

```{r}
write_csv(peds, "peds_cleaned.csv")
write_csv(peds_by_borough, "peds_by_borough.csv")
write_csv(brooklyn_bridge_totals, "brooklyn_bridge.csv")
write_csv(brooklyn_bridge_totals_t2, "brooklyn_bridge_transpose.csv")

```


